config/routes.rb
Rails.application.routes.draw do

  get 'answers/new'
  get 'favorites/index'
  get 'sessions/new'
  root 'pages#index'
  get 'pages/help'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :questions

  get "favorites/index"
  post "/favorites", to: "favorites#create"
  delete "/favorites", to: "favorites#destroy"

  resources :questions do
    resources :answers
  end
  resources :answers
end

app/models/question.rb
class Question < ApplicationRecord
  validates :user_id, presence:true
  validates :title, presence:true
  validates :content, presence:true
  validates :category, presence:true

  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  mount_uploader :url, UrlUploader

  has_one :questionnaire, dependent: :destroy
  accepts_nested_attributes_for :questionnaire

  has_many :favorites
  has_many :favorite_users, through: :favorites, source: "user"
  has_many :answers, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
    @question.build_questionnaire
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to questions_path, success: "投稿に成功しました"
    else
      flash[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    #質問選択肢に対する回答を円チャートで表示。円チャートは３種類作成
    #①回答選択肢(1 or 2)に対する回答集計結果　②①をさらに性別ごとに表示　③①を年齢ごとに表示
    arr_all = []
    arr_gender_num1 = []
    arr_gender_num2 = []
    arr_age_num1 = []
    arr_age_num2 = []
    @cnt_questionnaire1 = 0
    @cnt_questionnaire2 = 0
    @answers.each { |ans|
      arr_all.push(ans.questionnaire_number)
      if ans.questionnaire_number == 1
        @cnt_questionnaire1 += 1
        arr_gender_num1.push(ans.user.gender)
        arr_age_num1.push(Date.today.year - ans.user.age)
      else
        @cnt_questionnaire2 += 1
        arr_gender_num2.push(ans.user.gender)
        arr_age_num2.push(Date.today.year - ans.user.age)
      end
    }
    #①回答選択肢(1 or 2)に対する回答集計結果
    sum_all_num1 = arr_all.select{|n| n == 1}.size
    sum_all_num2 = arr_all.select{|n| n == 2}.size
    @data = {@question.questionnaire.option1 => sum_all_num1, @question.questionnaire.option2 => sum_all_num2}
    #②①をさらに性別ごとに表示
    sum_man_num1 = arr_gender_num1.select{|n| n == 1}.size
    sum_woman_num1 = arr_gender_num1.select{|n| n == 2}.size
    sum_man_num2 = arr_gender_num2.select{|n| n == 1}.size
    sum_woman_num2 = arr_gender_num2.select{|n| n == 2}.size
    @data_gender_num1 = {'男性' => sum_man_num1, '女性' => sum_woman_num1}
    @data_gender_num2 = {'男性' => sum_man_num2, '女性' => sum_woman_num2}
    #③①をさらに年齢ごとに表示
    sum_10_num1 = 0
    sum_20_num1 = 0
    sum_30_num1 = 0
    sum_40_num1 = 0
    sum_50_num1 = 0
    sum_60_num1 = 0
    sum_el_num1 = 0
    sum_10_num2 = 0
    sum_20_num2 = 0
    sum_30_num2 = 0
    sum_40_num2 = 0
    sum_50_num2 = 0
    sum_60_num2 = 0
    sum_el_num2 = 0

    arr_age_num1.each { |n|
      if n >= 10 && n <=19
        sum_10_num1 += 1
      elsif n >= 20 && n <=29
        sum_20_num1 += 1
      elsif n >= 30 && n <=39
        sum_30_num1 += 1
      elsif n >= 40 && n <=49
        sum_40_num1 += 1
      elsif n >= 50 && n <=59
        sum_50_num1 += 1
      elsif n >= 60 && n <=69
        sum_60_num1 += 1
      else
        sum_el_num1 += 1
      end
      }
      arr_age_num2.each { |n|
        if n >= 10 && n <=19
          sum_10_num2 += 1
        elsif n >= 20 && n <=29
          sum_20_num2 += 1
        elsif n >= 30 && n <=39
          sum_30_num2 += 1
        elsif n >= 40 && n <=49
          sum_40_num2 += 1
        elsif n >= 50 && n <=59
          sum_50_num2 += 1
        elsif n >= 60 && n <=69
          sum_60_num2 += 1
        else
          sum_el_num2 += 1
        end
        }
    @data_age_num1 = {'10代' => sum_10_num1, '20代' => sum_20_num1, '30代' => sum_30_num1, '40代' => sum_40_num1, '50代' => sum_50_num1, '60代' => sum_60_num1, 'その他' => sum_el_num1}
    @data_age_num2 = {'10代' => sum_10_num2, '20代' => sum_20_num2, '30代' => sum_30_num2, '40代' => sum_40_num2, '50代' => sum_50_num2, '60代' => sum_60_num2, 'その他' => sum_el_num2}
  end

  def edit
    @question.update(question_params)
    redirect_to new_question_path, success: "投稿を更新しました"
  rescue
    render :new
  end

  def index
    @questions = Question.all
  end

  private
  def question_params
    params.require(:question).permit(:title, :content, :category, questionnaire_attributes: [:id, :question_id, :option1, :option2])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/index.html.slim
h2.question-author
  | 質問・疑問一覧

- @questions.each do |question|
  .question-index-wrapper
    .container
      .row
        .col-sm-8
          .question-index-single
            .user-area
              .col-xs-1.user-icon-center
                = image_tag question.user.icon_image.url,
                  src: 'Image Not Found',
                  onerror: 'this.error=null;this.src="icons/user_icon.png"',
                  class: "img-circle user-icon-center-img"
              .col-xs-10.user-question-content
                = link_to question.title, question_path(id: question.id)
                p = question.content.truncate(33)
                ul.user-margin-zero.clearfix
                    li.left = question.user.name
                    li.left = "[#{question.category}]"
                    li.left = "回答数:#{question.answers.count}"
                    li.right = l question.created_at

app/views/questions/new.html.slim
.question-author
  h2.question-title 質問する
  .question-index-wrapper
    .container
      .row
        .col-sm-offset-2.col-sm-8
          .question-index-single
            h3.answer-content
              | 質問内容
            .col-sm-offset-1.col-sm-10.answer-que.clearfix
              = form_with model: @question, local: true do |f|
                .col-sm-8
                  .form-group
                    = f.text_field :title, class:"form-control", placeholder: "質問のタイトル"
                .form_group
                  = f.text_area :content, size: "20x10", class:"form-control", placeholder: "質問内容をご記入ください"

                = f.fields_for :questionnaire do |i|
                  .questionnaire.margin-top-dis30
                    .col-sm-8
                      .form-group
                        = i.label :アンケート
                        = i.text_field :option1, class:"form-control", placeholder: "アンケートの選択肢１"
                        = i.text_field :option2, class:"form-control", placeholder: "アンケートの選択肢2"
                        = i.hidden_field :question_id, :value => @question.id
                      .image-category.margin-top-dis30
                        .form-group
                          = f.label :カテゴリ選択, class: "form-check-label dis-block"
                          = f.select :category, ["人間関係・人生相談", "生活・暮らし","家電・電化製品","パソコン・スマートフォン",
                                   "インターネット","趣味・娯楽","美容・ファッション","健康・病気","ビジネス・キャリア",
                                   "社会","お金","学問・教育","旅行・レジャー","その他"], :prompt => "選択してください", class: "form-control"
                .col-sm-offset-8.col-sm-4.margin-top-dis30
                  - if logged_in?
                    = f.submit "質問投稿", class: "btn btn-block btn-primary"
                  - else
                    = f.submit "ログイン", class: "btn btn-block btn-primary"

app/views/questions/show.html.slim
.question-author
  h2.question-title 質問・回答
  .question-index-wrapper
    .container
      .row
        .col-sm-offset-1.col-sm-8
          .question-index-single
            h2
              = @question.title
            ul.clearfix
              li.info = l @question.created_at
              li.info = "質問No.#{@question.id}"
              li.info = "[#{@question.category}]"
              li.info = "回答数:#{@question.answers.count}"
            .user-area.clearfix
              .col-xs-1
                = image_tag @question.user.icon_image.url,
                    src: 'Image Not Found',
                    onerror: 'this.error=null;this.src="icons/user_icon.png"',
                    class: "img-circle"
              p.name-area.col-xs-9.col-xs-offset-1
                = @question.user.name

            .q_desc
              = @question.content
            .option
              h3.option-top
                | 回答選択肢
              ul
                .option-size
                  li.option-design  = "1: #{@question.questionnaire.option1}"
                  li.option-design  = "2: #{@question.questionnaire.option2}"

            .col-xs-offset-4.col-xs-4.answer-que
              - if logged_in?
                = link_to "回答する", new_question_answer_path(question_id: @question.id), class: "btn btn-block btn-primary"
              - else
                = link_to "回答する", login_path, class: "btn btn-block btn-primary"
            .answer-area
              - if @question.answers.count == 0
                p.answer-noth 現在回答を募集中です
              - else
                .tabs
                  p[style="font-size: 24px;"] 回答集計結果
                  input#all[type="radio" name="tab_item" checked]
                  label.tab_item[for="all"]
                    | 総合
                  input#gender[type="radio" name="tab_item"]
                  label.tab_item[for="gender"]
                    | 男女別
                  input#age[type="radio" name="tab_item"]
                  label.tab_item[for="age"]
                    | 年齢別
                  #all_content.tab_content
                    .tab_content_description
                      p.c-txtsp.text-center
                        = pie_chart @data
                  #gender_content.tab_content
                    .tab_content_description
                      - if @cnt_questionnaire1 >= 1
                        p.c-txtsp.text-center
                          | 回答選択肢１を選んだ男女割合
                        = pie_chart @data_gender_num1
                      - else
                        p.c-txtsp.text-center
                          | 回答選択肢１を選んだ人はいません
                      - if @cnt_questionnaire2 >= 1
                        p.c-txtsp.text-center
                          | 回答選択肢２を選んだ男女割合
                        = pie_chart @data_gender_num2
                      - else
                          p.c-txtsp.text-center
                            | 回答選択肢２を選んだ人はいません
                  #age_content.tab_content
                    .tab_content_description
                      - if @cnt_questionnaire1 >= 1
                        p.c-txtsp.text-center
                          | 回答選択肢１を選んだ年齢割合
                        = pie_chart @data_age_num1
                      - else
                        p.c-txtsp.text-center
                          | 回答選択肢１を選んだ人はいません
                      - if @cnt_questionnaire2 >= 1
                        p.c-txtsp.text-center
                          | 回答選択肢２を選んだ年齢割合
                        = pie_chart @data_age_num2
                      - else
                        p.c-txtsp.text-center
                          | 回答選択肢２を選んだ人はいません

                h3 回答
                hr
              - @answers.each do |answer|
                ul.clearfix
                  li.side-right = l answer.created_at
                .user-area.clearfix
                  .col-xs-1
                    = image_tag answer.user.icon_image.url,
                        src: 'Image Not Found',
                        onerror: 'this.error=null;this.src="icons/user_icon.png"',
                        class: "user-icon-size img-circle"
                  p.name-area.col-xs-9.col-xs-offset-1
                    = answer.user.name
                .q_desc
                  = answer.sentence
                .option
                  h3.option-top
                    | 回答結果
                  - if answer.questionnaire_number == 1
                    = "1: #{answer.question.questionnaire.option1}"
                  -else
                    = "2: #{answer.question.questionnaire.option2}"
                hr